{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoError","stack":"MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\nodeapp\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:328:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\nodeapp\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:274:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\nodeapp\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1277:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","level":"warn","timestamp":"2017-06-03T08:30:00.300Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoError","stack":"MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\nodeapp\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:328:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\nodeapp\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:274:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\nodeapp\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1277:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","level":"warn","timestamp":"2017-06-03T08:30:00.316Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoError","stack":"MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\nodeapp\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:328:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\nodeapp\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:274:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\nodeapp\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1277:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","level":"warn","timestamp":"2017-06-03T08:30:00.316Z"}
